"""initial schema

Revision ID: 77c0efef3d84
Revises: 
Create Date: 2026-08-26 23:02:50.537832
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import app.db  # noqa: F401  (TZDateTime custom type used below)


revision: str = '77c0efef3d84'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('ended_at', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'DIAGNOSED', 'RECOVERING', 'RESOLVED', 'CLOSED', 'FALSE_POSITIVE', name='incident_status', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incident_severity', native_enum=False, length=32), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('detection_method', sa.String(length=64), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('deviation_pct', sa.Float(), nullable=True),
    sa.Column('window_start', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('window_end', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('detected_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('affected_payments_count', sa.Integer(), nullable=False),
    sa.Column('revenue_at_risk_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('simulator_run_id', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_detected_at'), 'incidents', ['detected_at'], unique=False)
    op.create_index(op.f('ix_incidents_metric'), 'incidents', ['metric'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_simulator_run_id'), 'incidents', ['simulator_run_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gateway_account_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('outcome', sa.Enum('ALLOWED', 'BLOCKED', 'REQUIRES_APPROVAL', name='policy_outcome', native_enum=False, length=32), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('rules_matched', sa.JSON(), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('decided_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_action_id'), 'policy_decisions', ['action_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_outcome'), 'policy_decisions', ['outcome'], unique=False)
    op.create_table('simulator_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scenario', sa.String(length=128), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulator_runs_scenario'), 'simulator_runs', ['scenario'], unique=False)
    op.create_index(op.f('ix_simulator_runs_status'), 'simulator_runs', ['status'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('gateway_event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('received_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_gateway_event_id'), 'webhook_events', ['gateway_event_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_processed'), 'webhook_events', ['processed'], unique=False)
    op.create_index(op.f('ix_webhook_events_received_at'), 'webhook_events', ['received_at'], unique=False)
    op.create_table('agent_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_reports_agent_name'), 'agent_reports', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_reports_incident_id'), 'agent_reports', ['incident_id'], unique=False)
    op.create_index(op.f('ix_agent_reports_status'), 'agent_reports', ['status'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('gateway_customer_id', sa.String(length=64), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_gateway_customer_id'), 'customers', ['gateway_customer_id'], unique=False)
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('predicted_cause', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_incident_id'), 'diagnoses', ['incident_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_predicted_cause'), 'diagnoses', ['predicted_cause'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('evaluation_type', sa.String(length=64), nullable=False),
    sa.Column('dataset', sa.String(length=255), nullable=False),
    sa.Column('simulator_run_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('started_at', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulator_run_id'], ['simulator_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_evaluation_type'), 'evaluation_runs', ['evaluation_type'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_simulator_run_id'), 'evaluation_runs', ['simulator_run_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_status'), 'evaluation_runs', ['status'], unique=False)
    op.create_table('incident_evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('collector', sa.String(length=64), nullable=False),
    sa.Column('collected_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_evidence_evidence_type'), 'incident_evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_incident_evidence_incident_id'), 'incident_evidence', ['incident_id'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prediction_type', sa.String(length=64), nullable=False),
    sa.Column('input_features', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_predictions_incident_id'), 'model_predictions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_model_predictions_model_name'), 'model_predictions', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_predictions_prediction_type'), 'model_predictions', ['prediction_type'], unique=False)
    op.create_table('simulator_ground_truth',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('simulator_run_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('truth', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulator_run_id'], ['simulator_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulator_run_id', 'entity_type', 'entity_id', name='uq_ground_truth_entity')
    )
    op.create_index(op.f('ix_simulator_ground_truth_simulator_run_id'), 'simulator_ground_truth', ['simulator_run_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('gateway_order_id', sa.String(length=64), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('receipt', sa.String(length=128), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_gateway_order_id'), 'orders', ['gateway_order_id'], unique=True)
    op.create_index(op.f('ix_orders_merchant_id'), 'orders', ['merchant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('gateway_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=True),
    sa.Column('current_period_start', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_customer_id'), 'subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_gateway_subscription_id'), 'subscriptions', ['gateway_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_merchant_id'), 'subscriptions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=64), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.Column('error_source', sa.String(length=32), nullable=True),
    sa.Column('captured', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('gateway_created_at', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_gateway_payment_id'), 'payments', ['gateway_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_merchant_id'), 'payments', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_payments_method'), 'payments', ['method'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_event_type'), 'payment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_events_occurred_at'), 'payment_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_payment_events_payment_id'), 'payment_events', ['payment_id'], unique=False)
    op.create_table('recovery_opportunities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('payment_id', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('subscription_id', sa.String(length=64), nullable=True),
    sa.Column('opportunity_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'POLICY_EVALUATED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTING', 'VERIFYING', 'RECOVERED', 'FAILED', 'UNKNOWN', 'CANCELLED', 'ESCALATED', name='opportunity_status', native_enum=False, length=32), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('expected_recovery_paise', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('expires_at', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_opportunities_customer_id'), 'recovery_opportunities', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_incident_id'), 'recovery_opportunities', ['incident_id'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_opportunity_type'), 'recovery_opportunities', ['opportunity_type'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_payment_id'), 'recovery_opportunities', ['payment_id'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_status'), 'recovery_opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_subscription_id'), 'recovery_opportunities', ['subscription_id'], unique=False)
    op.create_table('recovery_strategies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('opportunity_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.Enum('RETRY_PAYMENT', 'CREATE_PAYMENT_LINK', 'NOTIFY_CUSTOMER', 'EXTEND_GRACE_PERIOD', 'PAUSE_SUBSCRIPTION', 'RESUME_SUBSCRIPTION', 'REFUND', 'ESCALATE_HUMAN', 'NO_ACTION', name='strategy_action_type', native_enum=False, length=32), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('expected_recovery_paise', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('eligibility', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=64), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['recovery_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_strategies_opportunity_id'), 'recovery_strategies', ['opportunity_id'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('opportunity_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.Enum('RETRY_PAYMENT', 'CREATE_PAYMENT_LINK', 'NOTIFY_CUSTOMER', 'EXTEND_GRACE_PERIOD', 'PAUSE_SUBSCRIPTION', 'RESUME_SUBSCRIPTION', 'REFUND', 'ESCALATE_HUMAN', 'NO_ACTION', name='action_type', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'POLICY_EVALUATED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTING', 'VERIFYING', 'RECOVERED', 'FAILED', 'UNKNOWN', 'CANCELLED', 'ESCALATED', name='action_status', native_enum=False, length=32), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('policy_decision_id', sa.String(length=64), nullable=True),
    sa.Column('gateway_request_id', sa.String(length=128), nullable=True),
    sa.Column('gateway_response', sa.JSON(), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('proposed_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('decided_at', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('approved_at', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('executed_at', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('verified_at', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['recovery_opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_decision_id'], ['policy_decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['recovery_strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_actions_gateway_request_id'), 'recovery_actions', ['gateway_request_id'], unique=True)
    op.create_index(op.f('ix_recovery_actions_incident_id'), 'recovery_actions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_opportunity_id'), 'recovery_actions', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_policy_decision_id'), 'recovery_actions', ['policy_decision_id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_status'), 'recovery_actions', ['status'], unique=False)
    op.create_index(op.f('ix_recovery_actions_strategy_id'), 'recovery_actions', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_actions_strategy_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_status'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_policy_decision_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_opportunity_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_incident_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_gateway_request_id'), table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index(op.f('ix_recovery_strategies_opportunity_id'), table_name='recovery_strategies')
    op.drop_table('recovery_strategies')
    op.drop_index(op.f('ix_recovery_opportunities_subscription_id'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_status'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_payment_id'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_opportunity_type'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_incident_id'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_customer_id'), table_name='recovery_opportunities')
    op.drop_table('recovery_opportunities')
    op.drop_index(op.f('ix_payment_events_payment_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_occurred_at'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_event_type'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_merchant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_gateway_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_merchant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_gateway_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_orders_merchant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_gateway_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_simulator_ground_truth_simulator_run_id'), table_name='simulator_ground_truth')
    op.drop_table('simulator_ground_truth')
    op.drop_index(op.f('ix_model_predictions_prediction_type'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_model_name'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_incident_id'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_incident_evidence_incident_id'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_evidence_type'), table_name='incident_evidence')
    op.drop_table('incident_evidence')
    op.drop_index(op.f('ix_evaluation_runs_status'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_simulator_run_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_evaluation_type'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_diagnoses_predicted_cause'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_incident_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_gateway_customer_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_agent_reports_status'), table_name='agent_reports')
    op.drop_index(op.f('ix_agent_reports_incident_id'), table_name='agent_reports')
    op.drop_index(op.f('ix_agent_reports_agent_name'), table_name='agent_reports')
    op.drop_table('agent_reports')
    op.drop_index(op.f('ix_webhook_events_received_at'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_processed'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_gateway_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_simulator_runs_status'), table_name='simulator_runs')
    op.drop_index(op.f('ix_simulator_runs_scenario'), table_name='simulator_runs')
    op.drop_table('simulator_runs')
    op.drop_index(op.f('ix_policy_decisions_outcome'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_action_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_simulator_run_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_metric'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_detected_at'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
