"""worker outbox, audit hash chain, commerce hot-path indexes

Revision ID: a83af82e8438
Revises: b4e7a1c2d305
Create Date: 2026-09-01 17:13:29.101362

Consolidated wave-2 migration (autogenerated from Base.metadata at head
b4e7a1c2d305, then hand-reviewed):

- New table ``notification_outbox`` (app/models/notification.py, docs/worker.md,
  ADR 0011 P2): one row per queued customer notification. The recovery
  executor enqueues on a `notify_customer` action; the in-process worker
  delivers via the NotificationSender port and stamps SENT/FAILED with
  `delivered_via` provenance. Indexes cover the worker's poll path
  (status + due_at) and the environment/action/customer lookups.
- ``audit_logs`` gains nullable ``previous_hash`` / ``entry_hash``
  (VARCHAR(64)) — the hash chain stamped by the before_flush hook in
  app/models/system.py and verified by app/services/audit/verify.py. Rows
  predating the chain keep NULL hashes and verify as legacy-valid, so no
  backfill is needed.
- Non-unique hot-path indexes ``ix_payments_created_at`` and
  ``ix_orders_created_at`` (spec pinned in tests/test_model_indexes.py):
  range-filtered/sorted scans in the payments list, the revenue engine, and
  the opportunity builder.

Batch mode for the audit_logs ALTER so SQLite and Postgres emit equivalent
results, matching the b4e7a1c2d305 convention.
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import app.db  # noqa: F401  (TZDateTime custom type used below)


revision: str = 'a83af82e8438'
down_revision: str | None = 'b4e7a1c2d305'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        'notification_outbox',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('action_id', sa.String(length=64), nullable=True),
        sa.Column('customer_id', sa.String(length=64), nullable=True),
        sa.Column('channel', sa.String(length=32), nullable=False),
        sa.Column('payload', sa.JSON(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('PENDING', 'SENT', 'FAILED', name='notification_status',
                    native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column('attempts', sa.Integer(), nullable=False),
        sa.Column('due_at', app.db.TZDateTime(timezone=True), nullable=False),
        sa.Column('sent_at', app.db.TZDateTime(timezone=True), nullable=True),
        sa.Column('delivered_via', sa.String(length=64), nullable=True),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('environment', sa.String(length=16), server_default='research',
                  nullable=False),
        sa.Column('created_at', app.db.TZDateTime(timezone=True), nullable=False),
        sa.Column('updated_at', app.db.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['action_id'], ['recovery_actions.id'],
                                ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'],
                                ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_notification_outbox_action_id'),
                    'notification_outbox', ['action_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_customer_id'),
                    'notification_outbox', ['customer_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_due_at'),
                    'notification_outbox', ['due_at'], unique=False)
    op.create_index(op.f('ix_notification_outbox_environment'),
                    'notification_outbox', ['environment'], unique=False)
    op.create_index(op.f('ix_notification_outbox_status'),
                    'notification_outbox', ['status'], unique=False)

    # Hash chain — nullable; pre-chain rows keep NULLs and verify as
    # legacy-valid (no backfill).
    with op.batch_alter_table('audit_logs') as batch_op:
        batch_op.add_column(
            sa.Column('previous_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(
            sa.Column('entry_hash', sa.String(length=64), nullable=True))

    op.create_index('ix_orders_created_at', 'orders', ['created_at'],
                    unique=False)
    op.create_index('ix_payments_created_at', 'payments', ['created_at'],
                    unique=False)


def downgrade() -> None:
    op.drop_index('ix_payments_created_at', table_name='payments')
    op.drop_index('ix_orders_created_at', table_name='orders')

    with op.batch_alter_table('audit_logs') as batch_op:
        batch_op.drop_column('entry_hash')
        batch_op.drop_column('previous_hash')

    op.drop_index(op.f('ix_notification_outbox_status'),
                  table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_environment'),
                  table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_due_at'),
                  table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_customer_id'),
                  table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_action_id'),
                  table_name='notification_outbox')
    op.drop_table('notification_outbox')
